### PR TITLE
Add try statement in middleware for process_request

### PR DESCRIPTION
**Pull request by toryburgett**
This updates request in middleware in process_request, request.REQUEST depreciated: https://github.com/django-polymorphic/django-polymorphic/issues/164

### CODE REVIEW

**Comment by drodrz** [comment]
Code looks good.  Can you add `install_requires = ['django>=1.9']` to `setup.py` and bump the version number?

**Comment by Ta7eb** [comment]
Do you think we can squash this two commits to one ?

**Comment by toryburgett** [comment]
request.GET is backwards compatible: https://docs.djangoproject.com/en/1.7/ref/request-response/#django.http.HttpRequest.GET

this is tagged with 2.2.1

**Comment by toryburgett** [comment]
This merge request has been updated to remove the try statement because request.GET is backwards compatible

**Comment by drodrz** [comment]
Good catch, this looks good to me.  Anything else @Ta7eb ?

**Pull request merged**
